#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# python3.13 manage.py migrate
# python3.13 manage.py migrate_dynamodb

# exec python3.13 -m debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver_plus 0.0.0.0:8001
# exec python3.13 -W error manage.py runserver_plus 0.0.0.0:8001
exec tail -f /dev/null
