# Generated by Django 5.2.7 on 2026-01-12 17:01

import core.contrib.db.constraints
import core.contrib.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('refunds', '0001_initial'),
        ('revenue', '0001_initial'),
        ('tariff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(default='', max_length=6)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RefundTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=50)),
                ('article_no', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('packet_id', models.IntegerField(blank=True, db_column='packetid', null=True)),
                ('fare', core.contrib.db.fields.DecimalIntField(decimal_places=2, default=0.0, max_digits=8)),
                ('refund_amount', core.contrib.db.fields.DecimalIntField(decimal_places=2, default=0.0, max_digits=8)),
                ('line', models.CharField(choices=[('red', 'Red Line'), ('blue', 'Blue Line'), ('green', 'Green Line'), ('yellow', 'Yellow Line')], max_length=100)),
                ('from_station_id', models.IntegerField(blank=True, null=True)),
                ('from_station_type', models.SmallIntegerField(blank=True, choices=[(0, 'Dummy (NULL) Entry'), (1, 'Zone'), (2, 'Station'), (3, 'Connecting Service')], null=True)),
                ('to_station_id', models.IntegerField(blank=True, null=True)),
                ('to_station_type', models.SmallIntegerField(blank=True, choices=[(0, 'Dummy (NULL) Entry'), (1, 'Zone'), (2, 'Station'), (3, 'Connecting Service')], null=True)),
                ('pay_type_1', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('credit', 'Credit'), ('debit', 'Debit'), ('exchange', 'Exchange'), ('voucher', 'Voucher'), ('multi_payment', 'Multi-Payment'), ('tr_check', 'TR Check'), ('web', 'Web'), ('tsi_collection', 'TSI Collection'), ('deducted_from_refund', 'Deducted from refund')], max_length=100)),
                ('pay_type_2', models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check'), ('credit', 'Credit'), ('debit', 'Debit'), ('exchange', 'Exchange'), ('voucher', 'Voucher'), ('multi_payment', 'Multi-Payment'), ('tr_check', 'TR Check'), ('web', 'Web'), ('tsi_collection', 'TSI Collection'), ('deducted_from_refund', 'Deducted from refund')], max_length=100)),
                ('amount', core.contrib.db.fields.DecimalIntField(db_column='amount', decimal_places=2, default=0, max_digits=8)),
                ('from_station', models.ForeignObject(from_fields=('version', 'from_station_id', 'from_station_type'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refund_ticket_from_station', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_tickets', to='refunds.refund')),
                ('ticket_type', models.ForeignObject(from_fields=('version_id', 'packet_id'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_tickets', to='tariff.salespackets', to_fields=('version_id', 'packet_id'))),
                ('to_station', models.ForeignObject(from_fields=('version', 'from_station_id', 'to_station_type'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refund_ticket_to_station', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('version', models.ForeignKey(blank=True, db_column='versionid', null=True, on_delete=django.db.models.deletion.CASCADE, to='general.tariffversions')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_new', models.DateTimeField(auto_created=True, db_column='timenew')),
                ('sales_packet_id', models.IntegerField(db_column='tickettypeid', help_text='This field contains the packet ID for packet sales to determine under which packet a single transaction was made.', null=True)),
                ('form', models.CharField(choices=[('paperticket', 'Ticket'), ('eticket', 'eTix')], default='paperticket', max_length=12)),
                ('number', models.CharField(db_index=True, help_text='Decoded full ticket-number', max_length=20)),
                ('amount', core.contrib.db.fields.DecimalIntField(db_column='amount', decimal_places=2, help_text='This field is used for FARE-OPTION-AMOUNT', max_digits=8)),
                ('from_type', models.SmallIntegerField(blank=True, choices=[(0, 'Dummy (NULL) Entry'), (1, 'Zone'), (2, 'Station'), (3, 'Connecting Service')], db_column='fromtype', null=True)),
                ('from_station_id', models.IntegerField(blank=True, db_column='fromstation', help_text='for tickets with specified relations: source, destination and/or via (transfer) station. A via (transfer) station may be missing, if the sales transaction refers to direct connection.', null=True)),
                ('to_type', models.SmallIntegerField(blank=True, choices=[(0, 'Dummy (NULL) Entry'), (1, 'Zone'), (2, 'Station'), (3, 'Connecting Service')], db_column='totype', null=True)),
                ('to_station_id', models.IntegerField(blank=True, db_column='tostation', help_text='for tickets with specified relations: source, destination and/or via (transfer) station. A via (transfer) station may be missing, if the sales transaction refers to direct connection.', null=True)),
                ('valid_from', models.DateTimeField(db_column='validfrom', help_text='contains FARE-OPTION_VALID-ON-DATE')),
                ('valid_to', models.DateTimeField(db_column='validto', help_text='contains FARE-OPTION_VALID-OFF-DATE')),
                ('count', models.IntegerField(default=1, help_text='Total number of trips')),
                ('device_id', models.IntegerField(blank=True, db_column='deviceid', help_text='Unique Tvm ID 1-999999', null=True)),
                ('unique_ms_id', models.IntegerField(blank=True, db_column='uniquemsid', help_text="Unique Main Shift ID, this ID is unique for each Device, it is steadily incremented, even if Device is set back (047'er)", null=True)),
                ('sales_transaction_no', models.IntegerField(blank=True, db_column='salestransactionno', help_text='Running Transaction Number, unique for a device', null=True)),
                ('sales_detail_ev_sequ_no', models.IntegerField(blank=True, db_column='salesdetailevsequno', help_text='Running Event Number, unique for a device', null=True)),
                ('correction_counter', models.IntegerField(db_column='correctioncounter', help_text='Counter to display a modified sales record by GUI', null=True)),
                ('device_class', models.ForeignKey(blank=True, db_column='deviceclassid', help_text='unique identifier of DeviceClass', null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.deviceclass')),
                ('from_station', models.ForeignObject(editable=False, from_fields=('version', 'from_station_id', 'from_type'), on_delete=django.db.models.deletion.PROTECT, related_name='ticket_from_station', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('sales_detail', models.ForeignObject(from_fields=('device_class', 'device_id', 'unique_ms_id', 'sales_transaction_no', 'sales_detail_ev_sequ_no', 'correction_counter'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', serialize=False, to='revenue.salesdetail', to_fields=('device_class', 'device_id', 'unique_ms_id', 'sales_transaction_no', 'sales_detail_ev_sequ_no', 'correction_counter'))),
                ('sales_packet', models.ForeignObject(editable=False, from_fields=('version', 'sales_packet_id'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='tariff.salespackets', to_fields=('version_id', 'packet_id'))),
                ('sales_transaction', models.ForeignObject(from_fields=('device_class', 'device_id', 'unique_ms_id', 'sales_transaction_no'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', serialize=False, to='revenue.salestransaction', to_fields=('device_class', 'device_id', 'unique_ms_id', 'sales_transaction_no'))),
                ('to_station', models.ForeignObject(editable=False, from_fields=('version', 'to_station_id', 'to_type'), on_delete=django.db.models.deletion.PROTECT, related_name='ticket_to_station', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('user_new', models.ForeignKey(db_column='usernew', on_delete=django.db.models.deletion.PROTECT, related_name='created_ticket_set', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(db_column='versionid', help_text='This field is used to store the tariff version for the sold article (tickettype)', on_delete=django.db.models.deletion.PROTECT, to='general.tariffversions')),
            ],
        ),
        migrations.CreateModel(
            name='PaperTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_packet_id', models.IntegerField(db_column='tickettypeid', null=True)),
                ('number', models.CharField(db_index=True, max_length=20)),
                ('amount', core.contrib.db.fields.DecimalIntField(db_column='amount', decimal_places=2, max_digits=8)),
                ('from_type', models.SmallIntegerField(blank=True, db_column='fromtype', null=True)),
                ('from_station_id', models.IntegerField(blank=True, db_column='fromstation', null=True)),
                ('to_type', models.SmallIntegerField(blank=True, db_column='totype', null=True)),
                ('to_station_id', models.IntegerField(blank=True, db_column='tostation', null=True)),
                ('via_type', models.SmallIntegerField(blank=True, db_column='viatype', null=True)),
                ('via_station_id', models.IntegerField(blank=True, db_column='viastation', null=True)),
                ('from_return_type', models.SmallIntegerField(blank=True, db_column='fromreturntype', null=True)),
                ('from_return_id', models.IntegerField(blank=True, db_column='fromreturn', null=True)),
                ('to_return_type', models.SmallIntegerField(blank=True, db_column='toreturntype', null=True)),
                ('to_return_id', models.IntegerField(blank=True, db_column='toreturn', null=True)),
                ('via_return_type', models.SmallIntegerField(blank=True, db_column='viareturntype', null=True)),
                ('via_return_id', models.IntegerField(blank=True, db_column='viareturn', null=True)),
                ('valid_from', models.DateTimeField(db_column='validfrom')),
                ('valid_to', models.DateTimeField(db_column='validto')),
                ('count_passenger_category_1', models.IntegerField(db_column='countpassengercategory1', default=1)),
                ('start_connection_service', models.IntegerField(db_column='startconnectionservice', default=0)),
                ('end_connection_service', models.IntegerField(db_column='endconnectionservice', default=0)),
                ('from_return', models.ForeignObject(from_fields=('version', 'from_return_id', 'from_return_type'), on_delete=django.db.models.deletion.PROTECT, related_name='paper_ticket_from_return', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('from_station', models.ForeignObject(from_fields=('version', 'from_station_id', 'from_type'), on_delete=django.db.models.deletion.PROTECT, related_name='paper_ticket_from_station', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('sales_packet', models.ForeignObject(from_fields=('version', 'sales_packet_id'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_tickets', to='tariff.salespackets', to_fields=('version_id', 'packet_id'))),
                ('to_return', models.ForeignObject(from_fields=('version', 'to_return_id', 'to_return_type'), on_delete=django.db.models.deletion.PROTECT, related_name='paper_ticket_to_return', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('to_station', models.ForeignObject(from_fields=('version', 'to_station_id', 'to_type'), on_delete=django.db.models.deletion.PROTECT, related_name='paper_ticket_to_station', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('version', models.ForeignKey(db_column='versionid', on_delete=django.db.models.deletion.CASCADE, to='general.tariffversions')),
                ('via_return', models.ForeignObject(editable=False, from_fields=('version', 'via_return_id', 'via_return_type'), on_delete=django.db.models.deletion.PROTECT, related_name='paper_ticket_via_return_station', serialize=False, to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('via_station', models.ForeignObject(from_fields=('version', 'via_station_id', 'via_type'), on_delete=django.db.models.deletion.PROTECT, related_name='paper_ticket_via_station', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('ticket', models.OneToOneField(db_column='ticketid', on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ETixTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_ticket_no', models.CharField(db_column='eticketno', max_length=12)),
                ('price', core.contrib.db.fields.DecimalIntField(db_column='price', decimal_places=2, max_digits=8)),
                ('discount_code', models.CharField(blank=True, db_column='discountcode', default='', max_length=20)),
                ('product_id', models.IntegerField(db_column='productid')),
                ('activate_start', models.DateTimeField(db_column='activatestart')),
                ('device_utc', models.DateTimeField(db_column='deviceutc')),
                ('from_type', models.SmallIntegerField(blank=True, db_column='fromtype', null=True)),
                ('from_station_id', models.IntegerField(blank=True, db_column='fromstation', null=True)),
                ('to_type', models.SmallIntegerField(blank=True, db_column='totype', null=True)),
                ('to_station_id', models.IntegerField(blank=True, db_column='tostation', null=True)),
                ('parent_product_id', models.CharField(db_column='parentproductid', max_length=8)),
                ('line', models.CharField(max_length=128)),
                ('abi', models.CharField(max_length=32)),
                ('act', models.SmallIntegerField(choices=[(-1, 'No action taken'), (4001, 'Validation Successful'), (5001, 'Finalized ticket action'), (5901, 'Step-up ticket'), (5902, 'Stend ticket validity'), (5904, 'Combined step-up and extend')])),
                ('tkt_oc', models.SmallIntegerField(db_column='tktoc')),
                ('from_station', models.ForeignObject(from_fields=('version', 'from_station_id', 'from_type'), on_delete=django.db.models.deletion.PROTECT, related_name='etix_ticket_from_station', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('to_station', models.ForeignObject(from_fields=('version', 'to_station_id', 'to_type'), on_delete=django.db.models.deletion.PROTECT, related_name='etix_ticket_to_station', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('version', models.ForeignKey(db_column='versionid', on_delete=django.db.models.deletion.DO_NOTHING, to='general.tariffversions')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_new', models.DateTimeField(auto_created=True, db_column='timenew')),
                ('tour_id', models.IntegerField(db_column='tourid', default=0)),
                ('conductor_id', models.IntegerField(db_column='conductorid', default=0)),
                ('train_id', models.IntegerField(db_column='trainid', default=0)),
                ('scanned_on', models.DateTimeField(db_column='scannedon', null=True)),
                ('scan_sync_time', models.BigIntegerField(db_column='scansynctime', default=0)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.company')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='ticket.ticket')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ticketsource')),
            ],
            options={
                'ordering': ['-scanned_on'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('emp_nbr', models.CharField(max_length=9)),
                ('crew_id', models.CharField(max_length=15)),
                ('tour_start', models.DateTimeField()),
                ('tour_end', models.DateTimeField(null=True)),
                ('system_date', models.DateTimeField()),
                ('force_close_tour', models.BooleanField(default=False)),
                ('car_number', models.CharField(max_length=10)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.company')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.position')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('version', 'from_station_id', 'from_type'), name='r_ticket_from_station', to='general.ZoneStation', to_fields=('version', 'zone_station_id', 'type')),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('version', 'to_station_id', 'to_type'), name='r_ticket_to_station', to='general.ZoneStation', to_fields=('version', 'zone_station_id', 'type')),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('version', 'sales_packet_id'), name='r_ticket_sales_packet', to='tariff.SalesPackets', to_fields=('version_id', 'packet_id')),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('device_class', 'device_id', 'unique_ms_id', 'sales_transaction_no'), name='r_ticket_sales_transaction', to='revenue.SalesTransaction', to_fields=('device_class', 'device_id', 'unique_ms_id', 'sales_transaction_no')),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('device_class', 'device_id', 'unique_ms_id', 'sales_transaction_no', 'sales_detail_ev_sequ_no', 'correction_counter'), name='r_ticket_sales_detail', to='revenue.SalesDetail', to_fields=('device_class', 'device_id', 'unique_ms_id', 'sales_transaction_no', 'sales_detail_ev_sequ_no', 'correction_counter')),
        ),
        migrations.AddConstraint(
            model_name='paperticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('version', 'sales_packet_id'), name='r_paper_ticket_sales_packet', to='tariff.SalesPackets', to_fields=('version_id', 'packet_id')),
        ),
        migrations.AddConstraint(
            model_name='paperticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('version', 'from_station_id', 'from_type'), name='r_paper_ticket_from_station', to='general.ZoneStation', to_fields=('version', 'zone_station_id', 'type')),
        ),
        migrations.AddConstraint(
            model_name='paperticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('version', 'to_station_id', 'to_type'), name='r_paper_ticket_to_station', to='general.ZoneStation', to_fields=('version', 'zone_station_id', 'type')),
        ),
        migrations.AddConstraint(
            model_name='paperticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('version', 'via_station_id', 'via_type'), name='r_paper_ticket_via_station', to='general.ZoneStation', to_fields=('version', 'zone_station_id', 'type')),
        ),
        migrations.AddConstraint(
            model_name='paperticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('version', 'from_return_id', 'from_return_type'), name='r_paper_ticket_from_return', to='general.ZoneStation', to_fields=('version', 'zone_station_id', 'type')),
        ),
        migrations.AddConstraint(
            model_name='paperticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('version', 'to_return_id', 'to_return_type'), name='r_paper_ticket_to_return', to='general.ZoneStation', to_fields=('version', 'zone_station_id', 'type')),
        ),
        migrations.AddConstraint(
            model_name='paperticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('version', 'via_return_id', 'via_return_type'), name='r_paper_ticket_via_return', to='general.ZoneStation', to_fields=('version', 'zone_station_id', 'type')),
        ),
        migrations.AddConstraint(
            model_name='etixticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('version', 'from_station_id', 'from_type'), name='r_etix_ticket_from_station', to='general.ZoneStation', to_fields=('version', 'zone_station_id', 'type')),
        ),
        migrations.AddConstraint(
            model_name='etixticket',
            constraint=core.contrib.db.constraints.ForeignReferencesConstraint(from_fields=('version', 'to_station_id', 'to_type'), name='r_etix_ticket_to_station', to='general.ZoneStation', to_fields=('version', 'zone_station_id', 'type')),
        ),
    ]
