# Generated by Django 5.2.7 on 2026-01-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefundTicket',
        ),
    ]
