# Generated by Django 5.2.7 on 2026-01-12 17:01

import core.contrib.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.CharField(blank=True, help_text='Sequence#', max_length=20, unique=True)),
                ('routing_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('re-open', 'Re-Open'), ('re-closed', 'Re-Closed')], default='open', max_length=15)),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('from_dept', models.CharField(choices=[('finance', 'Finance'), ('customer_service', 'Customer Service'), ('operations', 'Operations'), ('legal', 'Legal'), ('field_ops', 'Field Operations'), ('executive', 'Executive Management')], max_length=100)),
                ('route_to_dept', models.CharField(choices=[('finance', 'Finance'), ('customer_service', 'Customer Service'), ('operations', 'Operations'), ('legal', 'Legal'), ('field_ops', 'Field Operations'), ('executive', 'Executive Management')], max_length=100)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('identification_type', models.CharField(choices=[('normal', 'Normal')], max_length=200)),
                ('address_1', models.CharField(max_length=255)),
                ('lic_number', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('intl_zip', models.CharField(blank=True, max_length=20)),
                ('day_phone', models.CharField(blank=True, max_length=20)),
                ('evening_phone', models.CharField(blank=True, max_length=20)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('invalid_id', models.BooleanField(blank=True)),
                ('invalid_address', models.BooleanField(blank=True)),
                ('waived', models.BooleanField()),
                ('waived_reason', models.CharField(blank=True, choices=[('approved_by_cust_engagement', 'Approved By Cust Engagement'), ('approved_by_cust_engagement', 'Approved By Revenue Engagement')], max_length=100)),
                ('train_num', models.CharField(max_length=100)),
                ('ticket_type', models.CharField(choices=[('peak', 'Peak'), ('peak_half', 'Peak Half'), ('off_peak', 'Off Peak'), ('military', 'Military'), ('ten_trip_peak', 'Ten Trip Peak'), ('ten_trip_off_peak', 'Ten Trip Off Peak'), ('ten_trip_senior', 'Ten Trip Senior'), ('family', 'Family'), ('belmont', 'Belmont'), ('city_ticket', 'City Ticket'), ('special_event_rail', 'Special Event Rail'), ('hampton_reserve_seat', 'Hampton Reserve - Seat'), ('lost_and_found', 'Lost & Found'), ('mail_and_ride', 'Mail & Ride'), ('credit_overcharge', 'Credit Overcharge'), ('no_ticket_type_defined', 'No Ticket Type Defined'), ('uniticket_nyct', 'UniTicket NYCT'), ('uniticket_long_beach', 'UniTicket Long Beach'), ('uniticket_nice_bus', 'UniTicket NICE Bus'), ('uniticket_mta_bus', 'UniTicket MTA Bus'), ('overpayment_school', 'Overpayment (School)'), ('ny_metro_card', 'NY Metro Card'), ('nyct_metro_card', 'NYCT Metro Card'), ('nyc_ui_getaway_vendors', 'NYC/UI Getaway Vendors'), ('tsm_web_unticket_subsidy', 'TSM/Web UniTicket Subsidy'), ('mail_and_ride_unlimited', 'Mail & Ride Unlimited'), ('refund_processing_fee', 'Refund Processing Fee')], max_length=100)),
                ('invoice_date', models.DateField()),
                ('bill_num', models.CharField(max_length=100)),
                ('line', models.CharField(choices=[('summary_branch', 'Summary Branch'), ('port_jefferson_branch', 'Port Jefferson Branch'), ('oyster_bay_branch', 'Oyster Bay Branch'), ('port_washington_branch', 'Port Washington Branch'), ('hempstead_branch', 'Hempstead Branch'), ('babylon_branch', 'Babylon Branch'), ('far_rockaway_branch', 'Far Rockaway Branch'), ('west_hempstead_branch', 'West Hempstead Branch'), ('city_zone_branch', 'City Zone Branch'), ('long_beach_branch', 'Long Beach Branch'), ('ronkonkoma_branch', 'Ronkonkoma Branch'), ('hempstead_branch', 'Hempstead Branch'), ('greenport_branch', 'Greenport Branch')], max_length=100)),
                ('from_station', models.CharField(choices=[('STN01', 'Central Station'), ('STN02', 'North Station'), ('STN03', 'East Station'), ('STN04', 'West Station')], max_length=100)),
                ('to_station', models.CharField(choices=[('STN01', 'Central Station'), ('STN02', 'North Station'), ('STN03', 'East Station'), ('STN04', 'West Station')], max_length=100)),
                ('amount_due', core.contrib.db.fields.DecimalIntField(decimal_places=2, default=0.0, max_digits=8)),
                ('amount_paid', core.contrib.db.fields.DecimalIntField(decimal_places=2, default=0.0, max_digits=8)),
                ('balance', core.contrib.db.fields.DecimalIntField(decimal_places=2, default=0.0, max_digits=8)),
                ('letter_print_batch', models.CharField(blank=True, max_length=100)),
                ('letter_sent_date', models.DateField(blank=True, null=True)),
                ('letter_generated_date', models.DateField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('credit', 'Credit'), ('debit', 'Debit'), ('exchange', 'Exchange'), ('voucher', 'Voucher'), ('multi_payment', 'Multi-Payment'), ('tr_check', 'TR Check'), ('web', 'Web'), ('tsi_collection', 'TSI Collection'), ('deducted_from_refund', 'Deducted from refund')], max_length=50)),
                ('check_number', models.CharField(blank=True, max_length=50)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('is_manual_payment', models.BooleanField(default=False)),
                ('reason_for_non_payment', models.CharField(choices=[('forgot_money', 'Forgot Money')], max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('conductor_emp_num', models.CharField(max_length=100)),
                ('conductor_name', models.CharField(blank=True, max_length=100)),
                ('tim_num', models.CharField(blank=True, max_length=100)),
                ('shift_id', models.CharField(blank=True, max_length=100)),
                ('clerk_remarks', models.TextField(blank=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctp_from', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctp_updated', to=settings.AUTH_USER_MODEL)),
                ('originally_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctp_entered', to=settings.AUTH_USER_MODEL)),
                ('route_to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctp_routed_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
