# Generated by Django 5.2.7 on 2026-01-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Statuses'},
        ),
        migrations.AlterField(
            model_name='company',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='connectingservice',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='connectingservice',
            name='time_new',
            field=models.DateTimeField(auto_now_add=True, db_column='timenew', null=True),
        ),
        migrations.AlterField(
            model_name='connectingservice',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid?'),
        ),
        migrations.AlterField(
            model_name='country',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='time_new',
            field=models.DateTimeField(auto_now_add=True, db_column='timenew', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid?'),
        ),
        migrations.AlterField(
            model_name='department',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='time_new',
            field=models.DateTimeField(auto_now_add=True, db_column='timenew', null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid?'),
        ),
        migrations.AlterField(
            model_name='deviceclass',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='deviceclassgroup',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='stationgroup',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='stationrouteelements',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='time_new',
            field=models.DateTimeField(auto_now_add=True, db_column='timenew', null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid?'),
        ),
        migrations.AlterField(
            model_name='timelock',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='timelockgroup',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='tvmstation',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', help_text='Date and time of changing entry', null=True),
        ),
        migrations.AlterField(
            model_name='validity',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
    ]
