# Generated by Django 5.2.7 on 2026-01-12 17:01

import core.contrib.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotifiedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_new', models.DateTimeField(blank=True, db_column='timenew', null=True)),
                ('time_change', models.DateTimeField(blank=True, db_column='timechange', null=True)),
                ('valid', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
                ('user_change', models.ForeignKey(db_column='userchange', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('user_new', models.ForeignKey(db_column='usernew', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_notified_by',
            },
        ),
        migrations.CreateModel(
            name='NotifiedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_new', models.DateTimeField(blank=True, db_column='timenew', null=True)),
                ('time_change', models.DateTimeField(blank=True, db_column='timechange', null=True)),
                ('valid', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
                ('user_change', models.ForeignKey(db_column='userchange', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('user_new', models.ForeignKey(db_column='usernew', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notified_by',
            },
        ),
        migrations.CreateModel(
            name='RefundJustification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_new', models.DateTimeField(blank=True, db_column='timenew', null=True)),
                ('time_change', models.DateTimeField(blank=True, db_column='timechange', null=True)),
                ('valid', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
                ('denial_description', models.CharField(max_length=255)),
                ('user_change', models.ForeignKey(db_column='userchange', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('user_new', models.ForeignKey(db_column='usernew', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refund_justifications',
            },
        ),
        migrations.CreateModel(
            name='RefundReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_new', models.DateTimeField(blank=True, db_column='timenew', null=True)),
                ('time_change', models.DateTimeField(blank=True, db_column='timechange', null=True)),
                ('valid', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
                ('user_change', models.ForeignKey(db_column='userchange', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('user_new', models.ForeignKey(db_column='usernew', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refund_reasons',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.CharField(blank=True, help_text='Sequence#', max_length=20, unique=True)),
                ('routing_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('re-open', 'Re-Open'), ('re-closed', 'Re-Closed')], default='open', max_length=15)),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('intl_zip', models.CharField(blank=True, max_length=20)),
                ('day_phone', models.CharField(blank=True, max_length=20)),
                ('evening_phone', models.CharField(blank=True, max_length=20)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('form_number', models.CharField(blank=True, max_length=50)),
                ('status_date', models.DateTimeField(blank=True, null=True)),
                ('reason_text', models.TextField(blank=True)),
                ('purchased_date_time', models.DateTimeField(null=True)),
                ('loose_ticket', models.BooleanField(default=False)),
                ('cust_service_petty_cash', models.BooleanField(default=False)),
                ('other_connecting_service', models.CharField(blank=True, max_length=100)),
                ('purchase_type', models.CharField(blank=True, choices=[('tss_refund', 'TSS Refund'), ('etix_refund', 'eTix Refund'), ('group_sales_refund', 'Group Sales Refund'), ('stims_obtims_manual', 'STIMS,OBTIMS,Manual'), ('hampton_holiday', 'Hampton/Holiday'), ('mail_ride_refunds', 'MailRide Refunds')], max_length=50)),
                ('card_type', models.CharField(blank=True, choices=[('discover', 'Discover'), ('mastercard', 'MasterCard'), ('visa', 'Visa'), ('american_express', 'American Express')], max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=50)),
                ('exp_year', models.CharField(blank=True, max_length=5)),
                ('exp_month', models.CharField(blank=True, max_length=3)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('order_reference', models.CharField(blank=True, max_length=100)),
                ('date_recorded_by_station', models.DateTimeField(blank=True, null=True)),
                ('sent_for_processing', models.CharField(blank=True, choices=[('accounting', 'Accounting'), ('revenue', 'Revenue')], max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('check_number', models.CharField(blank=True, max_length=50)),
                ('amount_refunded', core.contrib.db.fields.DecimalIntField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('total_amount_of_refund', core.contrib.db.fields.DecimalIntField(decimal_places=2, default=0.0, max_digits=8)),
                ('fee', core.contrib.db.fields.DecimalIntField(decimal_places=2, default=10.0, max_digits=8)),
                ('final_refund', core.contrib.db.fields.DecimalIntField(decimal_places=2, default=0.0, max_digits=8)),
                ('company', models.ForeignKey(db_column='company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_company_id', to='general.company')),
                ('connecting_service', models.ForeignKey(db_column='connecting_service_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_connecting_service', to='general.connectingservice')),
                ('country', models.ForeignKey(db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_country', to='general.country')),
                ('current_status', models.ForeignKey(db_column='current_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_status', to='general.status')),
                ('cust_notified_by', models.ForeignKey(db_column='cust_notified_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_customers_notified_by', to='refunds.customernotifiedby')),
                ('from_dept', models.ForeignKey(db_column='from_dept_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_from_department', to='general.department')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_from', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_updated', to=settings.AUTH_USER_MODEL)),
                ('notified_by', models.ForeignKey(db_column='notified_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_notified_by', to='refunds.notifiedby')),
                ('originally_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_entered', to=settings.AUTH_USER_MODEL)),
                ('route_to_dept', models.ForeignKey(db_column='route_to_dept_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_to_department', to='general.department')),
                ('route_to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_routed_to', to=settings.AUTH_USER_MODEL)),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_status_changed', to=settings.AUTH_USER_MODEL)),
                ('approval_justification', models.ForeignKey(db_column='approval_justification_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_approval_justification', to='refunds.refundjustification')),
                ('denial_justification', models.ForeignKey(db_column='denial_justification_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_denial_justification', to='refunds.refundjustification')),
                ('refund_reason', models.ForeignKey(db_column='refund_reason_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_reason', to='refunds.refundreason')),
            ],
        ),
    ]
