# Generated by Django 5.2.7 on 2026-01-15 16:14

import core.contrib.db.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_country_options_alter_status_options_and_more'),
        ('refunds', '0001_initial'),
        ('tariff', '0001_initial'),
        ('ticket', '0002_delete_refundticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customernotifiedby',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='customernotifiedby',
            name='time_new',
            field=models.DateTimeField(auto_now_add=True, db_column='timenew', null=True),
        ),
        migrations.AlterField(
            model_name='customernotifiedby',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid?'),
        ),
        migrations.AlterField(
            model_name='notifiedby',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='notifiedby',
            name='time_new',
            field=models.DateTimeField(auto_now_add=True, db_column='timenew', null=True),
        ),
        migrations.AlterField(
            model_name='notifiedby',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid?'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='card_type',
            field=models.CharField(blank=True, choices=[(0, 'Discover'), (1, 'MasterCard'), (2, 'Visa'), (3, 'American Express')], max_length=50),
        ),
        migrations.AlterField(
            model_name='refund',
            name='title',
            field=models.CharField(blank=True, choices=[(0, 'Mr.'), (1, 'Mrs.'), (2, 'Ms.'), (3, 'Miss'), (4, 'Mx.'), (5, 'Dr.'), (6, 'Prof.')], max_length=20),
        ),
        migrations.AlterField(
            model_name='refundjustification',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='refundjustification',
            name='time_new',
            field=models.DateTimeField(auto_now_add=True, db_column='timenew', null=True),
        ),
        migrations.AlterField(
            model_name='refundjustification',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid?'),
        ),
        migrations.AlterField(
            model_name='refundreason',
            name='time_change',
            field=models.DateTimeField(auto_now=True, db_column='timechange', null=True),
        ),
        migrations.AlterField(
            model_name='refundreason',
            name='time_new',
            field=models.DateTimeField(auto_now_add=True, db_column='timenew', null=True),
        ),
        migrations.AlterField(
            model_name='refundreason',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid?'),
        ),
        migrations.CreateModel(
            name='RefundTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=50)),
                ('article_no', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('packet_id', models.IntegerField(blank=True, db_column='packetid', null=True)),
                ('fare', core.contrib.db.fields.DecimalIntField(decimal_places=2, default=0.0, max_digits=8)),
                ('refund_amount', core.contrib.db.fields.DecimalIntField(decimal_places=2, default=0.0, max_digits=8)),
                ('from_station_id', models.IntegerField(blank=True, null=True)),
                ('from_station_type', models.SmallIntegerField(blank=True, choices=[(0, 'Dummy (NULL) Entry'), (1, 'Zone'), (2, 'Station'), (3, 'Connecting Service')], null=True)),
                ('to_station_id', models.IntegerField(blank=True, null=True)),
                ('to_station_type', models.SmallIntegerField(blank=True, choices=[(0, 'Dummy (NULL) Entry'), (1, 'Zone'), (2, 'Station'), (3, 'Connecting Service')], null=True)),
                ('amount', core.contrib.db.fields.DecimalIntField(db_column='amount', decimal_places=2, default=0, max_digits=8)),
                ('pay_type_1', models.IntegerField(choices=[(0, 'Cash'), (1, 'Check'), (2, 'Credit'), (3, 'Debit'), (4, 'Exchange'), (5, 'Voucher'), (6, 'Multi-Payment'), (7, 'TR Check'), (8, 'Web'), (9, 'TSI Collection'), (10, 'Deducted from refund')])),
                ('pay_type_2', models.IntegerField(blank=True, choices=[(0, 'Cash'), (1, 'Check'), (2, 'Credit'), (3, 'Debit'), (4, 'Exchange'), (5, 'Voucher'), (6, 'Multi-Payment'), (7, 'TR Check'), (8, 'Web'), (9, 'TSI Collection'), (10, 'Deducted from refund')], null=True)),
                ('from_station', models.ForeignObject(from_fields=('version', 'from_station_id', 'from_station_type'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refund_ticket_from_station', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_tickets', to='refunds.refund')),
                ('sales_packet', models.ForeignObject(from_fields=('version_id', 'packet_id'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_tickets', to='tariff.salespackets', to_fields=('version_id', 'packet_id'))),
                ('ticket', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_tickets', to='ticket.ticket')),
                ('to_station', models.ForeignObject(from_fields=('version', 'from_station_id', 'to_station_type'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refund_ticket_to_station', to='general.zonestation', to_fields=('version', 'zone_station_id', 'type'))),
                ('version', models.ForeignKey(blank=True, db_column='versionid', null=True, on_delete=django.db.models.deletion.CASCADE, to='general.tariffversions')),
            ],
        ),
    ]
