# Generated by Django 5.2.7 on 2026-01-29 16:07

import core.contrib.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_alter_customernotifiedby_time_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('', '---'), ('tss_refund', 'TSS Refund'), ('etix_refund', 'eTix Refund'), ('group_sales_refund', 'Group Sales Refund'), ('obtims', 'OBTIMS'), ('stims_manual', 'STIMS,Manual'), ('hampton_holiday', 'Hampton/Holiday'), ('mail_ride_refunds', 'MailRide Refunds')], max_length=50),
        ),
        migrations.AlterField(
            model_name='refund',
            name='routing_status',
            field=models.CharField(choices=[('', '---'), ('open', 'Open'), ('closed', 'Closed'), ('re-open', 'Re-Open'), ('re-closed', 'Re-Closed')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='sent_for_processing',
            field=models.CharField(blank=True, choices=[('', '---'), ('accounting', 'Accounting'), ('revenue', 'Revenue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='refundticket',
            name='amount',
            field=core.contrib.db.fields.DecimalIntField(blank=True, db_column='amount', decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='refundticket',
            name='fare',
            field=core.contrib.db.fields.DecimalIntField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='refundticket',
            name='refund_amount',
            field=core.contrib.db.fields.DecimalIntField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
