#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# python /app/manage.py collectstatic --noinput
# python /app/manage.py migrate
# python /app/manage.py auto_createsuperuser

exec gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=${APP_HOME}
